swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/profile:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    patch:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - type: string
          in: header
          name: Authorization
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}:
    get:
      tags:
      - User Transactions
      summary: User's Account
      description: API for getting all accounts
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. User ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions:
    get:
      tags:
      - User Transactions
      summary: Transactions
      description: API for getting all transactions for the current month
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. User ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionsId}:
    get:
      tags:
      - User Transactions
      summary: Transaction details
      description: API for getting a single transaction details
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: integer
      responses:
        '200':
          description: Transaction retrieved successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. User ID/ transaction ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionsId}/transaction:
    post:
      tags:
      - User Transactions
      summary: Post an transaction informations
      description: API for posting transaction information 
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: integer
      - in: body
        name: body
        required: true
        description: Post transaction's informations
        schema:
            $ref: '#/definitions/TransactionsPost'
      responses:
        '200':
          description: Transaction posted successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. User ID/ transaction ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error
    patch:
      tags:
      - User Transactions
      summary: Update an existing transaction 
      description: API for updating a transaction's 
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: integer
      - in: body
        name: body
        required: true
        description: Update transaction's informations
        schema:
            $ref: '#/definitions/TransactionsUpdate'
      responses:
        '200':
          description: Transaction updated successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. User ID/ transaction ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error
    delete:
      tags:
      - User Transactions
      summary: Delete an existing transaction 
      description: API for deleting a transaction's 
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: integer
      - in: body
        name: body
        required: true
        description: Delete transaction's informations
        schema:
            $ref: '#/definitions/TransactionsDelete'
      responses:
        '200':
          description: Transaction deleted successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. User ID/ transaction ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionsId}/category:
    post:
      tags:
      - User Transactions
      summary: Post an transaction informations (category)
      description: API for posting transaction information category
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: integer
      - in: body
        name: body
        required: true
        description: Post transaction's informations
        schema:
            $ref: '#/definitions/TransactionsPostCategory'
      responses:
        '200':
          description: Transaction posted successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. User ID/ transaction ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error
    patch:
      tags:
      - User Transactions
      summary: Update an existing transaction (category)
      description: API for updating a transaction's category
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: integer
      - in: body
        name: body
        required: true
        description: Update transaction's informations
        schema:
            $ref: '#/definitions/TransactionsUpdateCategory'
      responses:
        '200':
          description: Transaction updated successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. User ID/ transaction ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error
    delete:
      tags:
      - User Transactions
      summary: Delete an existing transaction (category)
      description: API for deleting a transaction's category
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: integer
      - in: body
        name: body
        required: true
        description: Delete transaction's informations
        schema:
            $ref: '#/definitions/TransactionsDeleteCategory'
      responses:
        '200':
          description: Transaction deleted successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. User ID/ transaction ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error
  /user/accounts/{accountId}/transactions/{transactionsId}/notes:
    post:
      tags:
      - User Transactions
      summary: Post an transaction informations (notes)
      description: API for posting transaction information notes
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: integer
      - in: body
        name: body
        required: true
        description: Post transaction's informations
        schema:
            $ref: '#/definitions/TransactionsPostNotes'
      responses:
        '200':
          description: Transaction posted successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. User ID/ transaction ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error
    patch:
      tags:
      - User Transactions
      summary: Update an existing transaction (notes)
      description: API for updating a transaction's notes
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: integer
      - in: body
        name: body
        required: true
        description: Update transaction's informations
        schema:
            $ref: '#/definitions/TransactionsUpdateNotes'
      responses:
        '200':
          description: Transaction updated successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. User ID/ transaction ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error
    delete:
      tags:
      - User Transactions
      summary: Delete an existing transaction (notes)
      description: API for deleting a transaction's notes
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: header
        name: Authorization
        description: Attach Bearer JWT token
        type: string
        required: true
      - in: path
        name: accountId
        description: User's account ID
        type: integer
        required: true
      - in: path
        name: transactionsId
        description: Transaction's ID
        required: true
        type: integer
      - in: body
        name: body
        required: true
        description: Delete transaction's informations
        schema:
            $ref: '#/definitions/TransactionsDeleteNotes'
      responses:
        '200':
          description: Transaction deleted successully
          schema:
            $ref: '#/definitions/Transactions'
        '400':
          description: Bad request. User ID/ transaction ID must be an integer and larger than 0.
        '500':
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transactions:
    type: object
    properties:
      transactionsId:
        type: integer
        format: int64
      date:
        type: string
      description:
        type: string
      amount:
        type: number
      balance:
        type: string
      type:
        type: string
      category:
        type: string
      notes:
        type: string
  TransactionsPost:
    type: object
    properties:
      category:
        type: string
  TransactionsUpdate:
    type: object
    properties:
      category:
        type: string
  TransactionsDelete:
    type: object
    properties:
      category:
        type: string
  TransactionsPostCategory:
    type: object
    properties:
      category:
        type: string
  TransactionsUpdateCategory:
    type: object
    properties:
      category:
        type: string
  TransactionsDeleteCategory:
    type: object
    properties:
      category:
        type: string
  TransactionsPostNotes:
    type: object
    properties:
      notes:
        type: string
  TransactionsUpdateNotes:
    type: object
    properties:
      notes:
        type: string
  TransactionsDeleteNotes:
    type: object
    properties:
      notes:
        type: string